name: Generate Chart

on:
  push:
  workflow_dispatch:

# on:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run collect stats
        run: |
          python collect-stats.py

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm install chartjs-to-image
          npm install canvas

      - name: Generate chart png
        run: node generate-chart.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Add chart.png and data.json"
          git push
